### ISSUE TITLE
Activity dropped because the bot's endpoint is missing

### ISSUE THREAD

**Issue by rhalaly** [Azure-Samples/Cognitive-Services-Voice-Assistant#454] opened 2020-05-31 14:59 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Follow [this](https://docs.microsoft.com/en-us/azure/cognitive-services/Speech-Service/tutorial-voice-enable-your-bot-speech-sdk) tutorial.

### Any log messages given by the failure
> Activity dropped because the bot's endpoint is missing

### Expected/desired behavior
> Bot will work

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> V1.12.0

### Mention any other details that might be useful

I follow [this](https://docs.microsoft.com/en-us/azure/cognitive-services/Speech-Service/tutorial-voice-enable-your-bot-speech-sdk) tutorial. Everything works just fine, I can communicate with the bot on chat, but once I use the voice assistance tool (with subscription key and region), I see this error in azure portal:
![image](https://user-images.githubusercontent.com/8597700/83355478-6387ec80-a368-11ea-9731-8def716316aa.png)

**Comment by dargilco** [comment] 2020-06-02 15:06
Hi @rhalaly, thanks for opening this issue. Some questions/comments:
1. You mentioned following the "voice enable your bot" tutorial. When doing so, is it the sample echo bot you deployed, or a bot you've written yourself? 
2. When you say "I can communicate with the bot on chat", do you mean when you deploy it locally and test it using the Bot Framework Emulator (per section "Test the bot sample with the Bot Framework Emulator")?
3. Don't forget to [enable web socket connection](https://docs.microsoft.com/en-us/azure/cognitive-services/Speech-Service/tutorial-voice-enable-your-bot-speech-sdk#enable-web-sockets)
4. You can use [Windows Voice Assistant Clients ](https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/tree/master/clients/csharp-wpf) to communicate with your bot using voice or chat. Are you able to chat with your bot with this tool? Or do you get the same error "Activity dropped because the bot's endpoint is missing"?
5. The bot's endpoint is in the form https://EchoBot20190805125647.azurewebsites.net/api/messages/ . Don't forget the /api/messages part at the end... 
Thanks,
Darren

**Comment by rhalaly** [comment] 2020-06-02 15:23
Hi @dargilco here are the answers:

1. No, the EchoBot repo from the documentation itself.
2. Locally, and inside the Azure Blade (Test in Web Chat)
3. Enabled:
Here:
![image](https://user-images.githubusercontent.com/8597700/83537756-acbd7500-a4fd-11ea-9b0b-6a7c417183b2.png)
And Here:
![image](https://user-images.githubusercontent.com/8597700/83537784-b47d1980-a4fd-11ea-820b-46545788eacf.png)
4. Text doesn't work nether. Same error "Activity dropped because the bot's endpoint is missing" in the Direct Line Speech log.
5. Yes, it is 
![image](https://user-images.githubusercontent.com/8597700/83538024-045be080-a4fe-11ea-9630-56619912cee4.png)

**Comment by dargilco** [comment] 2020-06-02 15:29
@rhalaly Thank you for the quick response! We will try it out today to see if there are any regressions in the platform or changes made to the echo bot, and we will get back to you.

**Comment by chschrae** [comment] 2020-06-02 16:23
@rhalaly another thing to check and make sure is that the channels registration is set as described here: https://docs.microsoft.com/en-us/azure/cognitive-services/Speech-Service/tutorial-voice-enable-your-bot-speech-sdk#register-the-direct-line-speech-channel

Is yours set that way?

**Comment by rhalaly** [comment] 2020-06-02 16:34
Yes, I followed these steps

**Comment by dargilco** [comment] 2020-06-02 16:53
@rhalaly, I asked Sajjad (@splumber) to do the tutorial from scratch using his personal Azure subscription and it works fine for him, using latest version of Echo Bot. Voice and text chat via Windows Voice Assistant Client works for him. We need to figure out what's unique to your situation. What Azure region did you use? was it West US?

**Comment by rhalaly** [comment] 2020-06-02 16:59
Yes, West US. 

By the way, there is a missing step in the EchoBot. The `appsettings.json` is empty (withou the AppID and its Secret). Did you add these blank fields manually, or something wrong with the bot version (I just clone the repo in the tutorial and follow the steps)

**Comment by dargilco** [comment] 2020-06-02 17:17
There is no need to edit appsettings.json -- keep it the way it is when you clone the repo.

If you can share your unique bot handle, I will follow up with the proper folks here to look at telemetry associated with your error. The bot handle (or app  name) is the example EchoBot20190805125647 in the tutorial.

**Comment by rhalaly** [comment] 2020-06-02 17:30
Hmm, I had to fill these fields, otherwise the bot crashing. I will try to
clone and publish the EchoBot from the tutorial again and let you know how
it goes.

**Comment by dargilco** [comment] 2020-06-02 18:02
Are you using the [C# .NET Core echo bot](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/02.echo-bot) or one of the other programming languages?

**Comment by rhalaly** [comment] 2020-06-03 07:30
Yes, this one `samples\csharp_dotnetcore\02.echo-bot\EchoBot.sln` (as mentioned in the tutorial)

**Comment by rhalaly** [comment] 2020-06-03 07:43
I tried to redeploy the bot. Without entering the App Id and the Secret inside the `appsettings.json` file, I receive this error: "There was an error sending this message to your bot: HTTP status code Unauthorized"

![image](https://user-images.githubusercontent.com/8597700/83609388-e7b7bb00-a586-11ea-894b-1c58c98b2684.png)

In this [thread](https://github.com/microsoft/botframework-sdk/issues/4486), they said that probably the app id and the secret are missing. I will try to add them and update you

**Comment by rhalaly** [comment] 2020-06-03 07:54
Ok, so after entering the correct App Id and Secret, I was able to talk with the bot on the "Test in Web Chat" Azure blade:
![image](https://user-images.githubusercontent.com/8597700/83610573-521d2b00-a588-11ea-9b33-fe02c21a6a8b.png)

But now when I try to connect the Voice Assistant Client, the client immediately crashes...

**Comment by dargilco** [comment] 2020-06-03 15:56
Yes you need to update appssettings.json in order to test your bot in the web chat in the Azure portal. Since you are not the first to bring this up, I'm going to update the "voice enable your bot" tutorial with an optional section discussing this, even though it's not required for the bot to work with Direct Line Speech Channel and our sample client applications.
What is the pricing tier of the speech key you are using? It is listed in the "overview" section of the speech (Cognitive Service) Azure resource. Does it say "free" next to pricing tier?
There is a known bug in Speech SDK that causes a crash in Speech SDK, when Windows Voice Assistant Client gets an error from Direct Line Speech. I suspect you are hitting this bug. I am following up with the Speech SDK team. Windows Voice Assistant Client should display the error and not crash of course.
Still don't know why you are getting the error.. hence my question about pricing tier for the speech resource. Let me think of other experiments we can do to figure it out...

**Comment by rhalaly** [comment] 2020-06-03 16:04
The pricing tire is Standard:

![image](https://user-images.githubusercontent.com/8597700/83660031-faed7980-a5cc-11ea-8fbe-bf22ca0e3433.png)

**Comment by rhalaly** [comment] 2020-06-03 16:05
I will try to follow the tutorial from scratch again and see if I have some issue in my steps

**Comment by dargilco** [comment] 2020-06-08 18:48
@rhalaly I now have a repo of your reported issue. We found a bug in Speech SDK that resulted in the app crash you saw. When the fix is applied, the app does not crash, and it displays an error from the service instead of crashing. I'm still investigating why some folks see this error and some don't. The Speech SDK bug fix will be in the next version of Speech SDK. Updates are released roughly once a month. I'll update here when I find the reason for the service error.

**Comment by dargilco** [comment] 2020-06-09 19:49
Based on feedback from the service team, please make sure the "web sockets" is set to ON. Got to your EchoBot App Service in the Azure portal, click on "Configuration" under Settings, click on the "General settings" tab and set Web sockets to ON. Then click save and wait a few seconds for it to apply. Press the Reconnect button in Windows Voice Assistant client to reconnect. If you have done that and still see the crash, please reactivate this issue and we will continue the discussion. Closing the issue for now.

**Closed by dargilco** 2020-06-09 19:49 UTC
Labels: Customer reported, Windows Voice Assistant Client (C# WPF), bug

**Comment by rhalaly** [comment] 2020-06-09 19:53
There are already ON. You can see it in the picture above...

**Comment by dargilco** [comment] 2020-06-10 01:46
@rhalaly please toggle it to OFF, save, toggle it to ON, and save again. Then try again. If that does not work, unregister your bot from Direct Line Speech channel, and then register it again.

**Comment by Abdul-sattar03** [comment] 2021-03-16 18:51
hi there

this is the first time iam using bot service, 

error : 
![image](https://user-images.githubusercontent.com/38361626/111363990-b5330680-865e-11eb-902a-882c60fbab7a.png)

not sure what should i do now?
